### ISSUE TITLE
issue with grid and units 

### ISSUE THREAD

**Issue by manyorangeslices** [manyorangeslices/saas-website#2]
<img width="689" alt="Screen Shot 2020-04-20 at 3 50 05 PM" src="https://user-images.githubusercontent.com/55193113/79793468-a0e76c00-831e-11ea-93b4-4eb93450a299.png">

Markbot has an issue with my grids and units but I can't pinpoint the issue, could you please help me? 

@muxlowc

**Comment by muxlowc** [comment]
@manyorangeslices 

At this point in your code:
```
<main role="main" tabindex="0" class="pad-t-1-2">
    <div class="embed embed-4by3 banner unit xs-1 s-1 m-1 l-1">
```
You have a unit that needs a direct parent that is a grid, but doesn't - so you might might just need to add in another div in between your main and div with class of unit

```
<main role="main" tabindex="0" class="pad-t-1-2">
  <div class="grid">
    <div class="embed embed-4by3 banner unit xs-1 s-1 m-1 l-1">
```
etc.

Hope that helps!

**Comment by manyorangeslices** [comment]
<img width="517" alt="Screen Shot 2020-04-21 at 10 22 43 AM" src="https://user-images.githubusercontent.com/55193113/79877313-16544a80-83ba-11ea-9ee0-484c14788770.png">

How would I go about fixing these two? I do have the input id and names, and I tried putting an id and role on the div that wraps the content in my index. Thanks for your help.

@muxlowc

**Comment by muxlowc** [comment]
@manyorangeslices 

So you just need to switch a few tag names to fix this up. I've attached a screenshot of what your highlevel items should be. Your landmarks basically shouldn't be buried in your code, but rather be the highest level of code (I hope that makes sense). I think your header was wrapped in a div, as well as your main, plus you need to make your main larger, with multiple sections in it

<img width="953" alt="Screen Shot 2020-04-21 at 1 56 45 PM" src="https://user-images.githubusercontent.com/59422623/79897663-03e90980-83d8-11ea-9105-5dd518223085.png">

Let me know if this doesn't make sense !
