### ISSUE TITLE
problem with accessibility 

### ISSUE THREAD

**Issue by manyorangeslices** [manyorangeslices/saas-website#3]
<img width="517" alt="Screen Shot 2020-04-21 at 10 22 43 AM" src="https://user-images.githubusercontent.com/55193113/79882605-e0669480-83c0-11ea-93c5-db68315dbd49.png">

How would I go about fixing these two? I do have the input id and names, and I tried putting an id and role on the div that wraps the content in my index. Thanks for your help.

@muxlowc

**Comment by muxlowc** [comment]
@manyorangeslices  oops i commented on the other one you posted/closed!

**Comment by manyorangeslices** [comment]
@muxlowc your comment seemed to fix the big issue, but what should I do about the input issue? Thanks again.

**Comment by muxlowc** [comment]
@manyorangeslices ah it looks like you just need to add a name="email" or name="password" for all of your inputs on your sign-up page. These are usually more important for radio buttons, but you should still use them. You can see them in the example: https://learn-the-web.algonquindesign.ca/topics/forms-cheat-sheet/#examples

**Comment by manyorangeslices** [comment]
@muxlowc that fixed it thanks so much!
